#!/bin/sh

conf() {
  printf "$(c 0 0)
  $(c 0 31)os $(c 0 0) $(Os) 
  $(c 0 32)kr $(c 0 0) $(Kernel)
  $(c 0 33)wm $(c 0 0) $(Wm)
  $(c 0 34)sh $(c 0 0) $(Shell)
  $(c 0 35)ur $(c 0 0) $(User)
  $(c 0 36)up $(c 0 0) $(Uptime)
"
}
