#!/bin/sh

function start()
{
	$(which qs) kill
	env DISPLAY=:0 $(which qs) --daemonize
}

function startDebug()
{
	$(which qs) kill
	env DISPLAY=:0 $(which qs) 
}

function toggleBar()
{
	$(which qs) ipc call root toggleBar
}

function toggleLock()
{
	$(which qs) ipc call lock lock
}

function toggleLauncher() 
{
	$(which qs) ipc call root toggleLauncher
}

function setWall() {
	wall="$1"
	$(which qs) ipc call root setWallpaper $wall
}

function clearNotifs() {
	$(which qs) ipc call root clearNotifs
}


case $1 in
--start) start ;;
--debug) startDebug ;;
--setConfig) setConfig ;;
--toggleBar) toggleBar ;;
--toggleLauncher) toggleLauncher ;;
--lock) toggleLock ;;
--setWall) setWall $2 ;;
--clearNotifs) clearNotifs ;;
esac
