#!/bin/sh

function start()
{
	$(which qs) kill
	env DISPLAY=:0 $(which qs) --daemonize
}

function startDebug()
{
	$(which qs) kill
	env DISPLAY=:0 $(which qs) 
}

function toggleBar()
{
	$(which qs) ipc call root toggleBar
}

function toggleLock()
{
	$(which qs) ipc call lock lock
}

function toggleLauncher() 
{
	$(which qs) ipc call root toggleLauncher
}

function setWall() {
	wall="$1"
	pkill swaybg
	swaybg -m fill -i "$wall" > /dev/null 2>&1 & disown
	echo "#!/bin/sh" > ~/.config/labwc/wallset.sh
	echo "swaybg -m fill -i "$wall" & disown" >> ~/.config/labwc/wallset.sh
}

function clearNotifs() {
	$(which qs) ipc call root clearNotifs
}


case $1 in
--start) start ;;
--debug) startDebug ;;
--setConfig) setConfig ;;
--toggleBar) toggleBar ;;
--toggleLauncher) toggleLauncher ;;
--lock) toggleLock ;;
--setWall) setWall $2 ;;
--clearNotifs) clearNotifs ;;
esac
