#!/bin/sh
# Shitty i3lock-colors script by github.com/mehedirm6244
# Adapted by github.com/dealerofallthecats

declare -i SUSPEND
declare BG_PATH
declare bluetooth_before_status
BG_CACHED_PATH="${HOME}/.config/bspwm/lockscreen.png"

help() {
  echo "i3lock-color script by github/mehedirm6244"
  echo ""
  echo "Options:"
  echo "--help        Show this message"
  echo "--suspend     Suspend after locking"
  echo "--bg          Use the following image passed as argument as background"
  exit 0
}

create_cache() {
  size=$(xdpyinfo | grep dimensions | sed -r 's/^[^0-9]*([0-9]+x[0-9]+).*$/\1/')

  echo "[i] Caching background"
  eval convert "$BG_PATH" \
    -resize "$size""^" \
    -gravity center \
    -extent "$size" \
    -fill black \
    -colorize "60%" \
    "$BG_CACHED_PATH"
}


lock() {

  trans='00'
  semitrans='88'

  font='Product Sans Bold'

  i3lock \
    -n \
    --insidever-color=#c5c8c9$trans \
    --insidewrong-color=#c5c8c9$trans \
    --inside-color=#c5c8c9$trans \
    --ringver-color=#c5c8c9 \
    --ringwrong-color=#880000 \
    --ring-color=#c5c8c9$semitrans \
    --line-uses-inside \
    --keyhl-color=#c5c8c9 \
    --bshl-color=#c5c8c9 \
    --separator-color=#c5c8c9 \
    --verif-color=#c5c8c9 \
    --wrong-color=#880000 \
    --layout-color=#c5c8c9 \
    --date-color=#c5c8c9 \
    --time-color=#c5c8c9 \
    --image ${BG_CACHED_PATH} \
    --indicator \
    --verif-text="" \
    --wrong-text="" \
    --noinput="" \
    --lock-text="Locking..." \
    --lockfailed="Lock Failed" \
    --time-font=$font \
    --date-font=$font \
    --layout-font=$font \
    --verif-font=$font \
    --wrong-font=$font \
    --radius=15 \
    --ring-width=15 \
    --ind-pos="w/2:h/2+60" \
    --layout-pos="w/2:h-66" \
    --greeter-pos="w/2:h/2" \
    --pass-media-keys \
    --pass-screen-keys \
    --pass-volume-keys \
    --blur 5
}

openwidgets() {
 sleep 0.8
 eww open timelock
 eww open medialock
 eww open statuseslock
}

startlock() {
  lock &&
  eww close timelock
  eww close medialock
  eww close statuseslock

  if [[ "$bluetooth_before_status" != "on" ]]; then
    bluetoothctl power off
  fi
}

# Read arguements provided
case "$1" in
--bg)
  BG_PATH="$2"
  create_cache
  exit 0
  ;;
--help)
  help
  ;;
--suspend) SUSPEND=1 ;;
esac

bluetooth_before_status=$(bluetoothctl show | grep 'PowerState' | tr -d 'PwerState: \t' | tail -c+2)

startlock &

openwidgets open

if [[ ${SUSPEND} == 1 ]]; then
    systemctl suspend 
fi

