#!/bin/sh

cache_file=$HOME/.cache/redshift_state

get_state() {
  cat "$cache_file"
}

disable_redshift() {
  redshift -x >/dev/null 2>&1
  echo Off >"$cache_file"
}

enable_redshift() {
  redshift -x
  redshift -O 4500
  echo On >"$cache_file"
}

toggle() {
  if [[ $(get_state) == "On" ]]; then
    disable_redshift
  else
    enable_redshift
  fi
}


case $1 in
--info) echo "$(get_state)" ;;
*) toggle ;;
esac
